services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: npm install
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false